// AUTO-GENERATED FILE - DO NOT EDIT
// Generated from stdlib/*.cmel files by tools/embed_stdlib.sh
// This file is tracked in git for build convenience

#include "stdlib_embedded.h"

static const char STDLIB_LIST_SOURCE[] = 
"export fun createListWithDefaults(defaultElement, size) {\n"
"    var newList = [];\n"
"    for (var i = 0; i < size; i = i+1) {\n"
"        newList.add(defaultElement);\n"
"    }\n"
"    return newList;\n"
"}\n"
"\n"
"fun merge(nums, left, mid, right) {\n"
"    var n1 = mid - left + 1;\n"
"    var n2 = right - mid;\n"
"\n"
"    var leftTmp = createListWithDefaults(0, n1);\n"
"    var rightTmp = createListWithDefaults(0, n2);\n"
"\n"
"    for (var i = 0; i < n1; i = i+1) {\n"
"        leftTmp[i] = nums[left + i];\n"
"    }\n"
"    for (var i = 0; i < n2; i = i+1) {\n"
"        rightTmp[i] = nums[mid + 1 + i];\n"
"    }\n"
"\n"
"    var i = 0;\n"
"    var j = 0;\n"
"    var k = left;\n"
"\n"
"    while (i < n1 and j < n2) {\n"
"        if (leftTmp[i] <= rightTmp[j]) {\n"
"            nums[k] = leftTmp[i];\n"
"            i = i + 1;\n"
"        } else {\n"
"            nums[k] = rightTmp[j];\n"
"            j = j + 1;\n"
"        }\n"
"        k = k + 1;\n"
"    }\n"
"\n"
"    while (i < n1) {\n"
"        nums[k] = leftTmp[i];\n"
"        i = i + 1;\n"
"        k = k + 1;\n"
"    }\n"
"\n"
"    while (j < n2) {\n"
"        nums[k] = rightTmp[j];\n"
"        j = j + 1;\n"
"        k = k + 1;\n"
"    }\n"
"\n"
"    return nums;\n"
"}\n"
"\n"
"fun mergeWithComparator(nums, left, mid, right, comparator) {\n"
"    var n1 = mid - left + 1;\n"
"    var n2 = right - mid;\n"
"\n"
"    var leftTmp = createListWithDefaults(0, n1);\n"
"    var rightTmp = createListWithDefaults(0, n2);\n"
"\n"
"    for (var i = 0; i < n1; i = i+1) {\n"
"        leftTmp[i] = nums[left + i];\n"
"    }\n"
"    for (var i = 0; i < n2; i = i+1) {\n"
"        rightTmp[i] = nums[mid + 1 + i];\n"
"    }\n"
"\n"
"    var i = 0;\n"
"    var j = 0;\n"
"    var k = left;\n"
"\n"
"    while (i < n1 and j < n2) {\n"
"        if (comparator(leftTmp[i], rightTmp[j]) <= 0) {\n"
"            nums[k] = leftTmp[i];\n"
"            i = i + 1;\n"
"        } else {\n"
"            nums[k] = rightTmp[j];\n"
"            j = j + 1;\n"
"        }\n"
"        k = k + 1;\n"
"    }\n"
"\n"
"    while (i < n1) {\n"
"        nums[k] = leftTmp[i];\n"
"        i = i + 1;\n"
"        k = k + 1;\n"
"    }\n"
"\n"
"    while (j < n2) {\n"
"        nums[k] = rightTmp[j];\n"
"        j = j + 1;\n"
"        k = k + 1;\n"
"    }\n"
"\n"
"    return nums;\n"
"}\n"
"\n"
"fun mergeSort(nums, left, right) {\n"
"    if (left < right) {\n"
"        var mid = left + (right - left) / 2;\n"
"        // floor the number. Needs better approach\n"
"        mid = \"\" + mid;\n"
"        mid = mid.split(\".\");\n"
"        mid = number(mid[0]);\n"
"\n"
"        mergeSort(nums, left, mid);\n"
"        mergeSort(nums, mid + 1, right);\n"
"\n"
"        return merge(nums, left, mid, right);\n"
"    }\n"
"    return nums;\n"
"}\n"
"\n"
"fun mergeSortWithComparator(nums, left, right, comparator) {\n"
"    if (left < right) {\n"
"        var mid = left + (right - left) / 2;\n"
"        // floor the number. Needs better approach\n"
"        mid = \"\" + mid;\n"
"        mid = mid.split(\".\");\n"
"        mid = number(mid[0]);\n"
"\n"
"        mergeSortWithComparator(nums, left, mid, comparator);\n"
"        mergeSortWithComparator(nums, mid + 1, right, comparator);\n"
"\n"
"        return mergeWithComparator(nums, left, mid, right, comparator);\n"
"    }\n"
"    return nums;\n"
"}\n"
"\n"
"export fun sort(nums) {\n"
"    return mergeSort(nums, 0, nums.length() - 1);\n"
"}\n"
"\n"
"export fun sortWith(nums, comparator) {\n"
"    return mergeSortWithComparator(nums, 0, nums.length() - 1, comparator);\n"
"}\n"
"\n"
"export fun slice(list, start, end) {\n"
"    var newList = [];\n"
"    for (var i=start; i<end; i=i+1) {\n"
"        newList.add(list[i]);\n"
"    }\n"
"    return newList;\n"
"}\n"
;

static const char STDLIB_MATH_SOURCE[] = 
"// Math utilities\n"
"\n"
"export var PI = 3.14159265359;\n"
"export var E = 2.71828182846;\n"
"\n"
"export fun abs(x) {\n"
"    if (x < 0) return -x;\n"
"    return x;\n"
"}\n"
"\n"
"export fun max(a, b) {\n"
"    if (a > b) return a;\n"
"    return b;\n"
"}\n"
"\n"
"export fun min(a, b) {\n"
"    if (a < b) return a;\n"
"    return b;\n"
"}\n"
"\n"
"export fun pow(base, exp) {\n"
"    var result = 1;\n"
"    for (var i = 0; i < exp; i = i + 1) {\n"
"        result = result * base;\n"
"    }\n"
"    return result;\n"
"}\n"
"\n"
"export fun sqrt(x) {\n"
"    if (x < 0) return nil;\n"
"    if (x == 0) return 0;\n"
"\n"
"    var guess = x / 2;\n"
"    var epsilon = 0.00001;\n"
"\n"
"    while (abs(guess * guess - x) > epsilon) {\n"
"        guess = (guess + x / guess) / 2;\n"
"    }\n"
"\n"
"    return guess;\n"
"}\n"
;

static const char STDLIB_STRING_SOURCE[] = 
"// String utilities\n"
"\n"
"export fun join(list, delimiter) {\n"
"    if (list.length() == 0) return \"\";\n"
"\n"
"    var result = \"\";\n"
"    for (var i = 0; i < list.length(); i = i + 1) {\n"
"        result = result + list[i];\n"
"        if (i < list.length() - 1) {\n"
"            result = result + delimiter;\n"
"        }\n"
"    }\n"
"    return result;\n"
"}\n"
"\n"
"export fun reverse(str) {\n"
"    var chars = str.split(\"\");\n"
"    var result = \"\";\n"
"    for (var i = chars.length() - 1; i >= 0; i = i - 1) {\n"
"        result = result + chars[i];\n"
"    }\n"
"    return result;\n"
"}\n"
"\n"
"export fun startsWith(str, prefix) {\n"
"    if (prefix.length() > str.length()) return false;\n"
"\n"
"    var strPrefix = \"\";\n"
"    var chars = str.split(\"\");\n"
"    for (var i = 0; i < prefix.length(); i = i + 1) {\n"
"        strPrefix = strPrefix + chars[i];\n"
"    }\n"
"\n"
"    return strPrefix == prefix;\n"
"}\n"
"\n"
"export fun endsWith(str, suffix) {\n"
"    if (suffix.length() > str.length()) return false;\n"
"\n"
"    var strSuffix = \"\";\n"
"    var chars = str.split(\"\");\n"
"    for (var i = str.length() - suffix.length(); i < str.length(); i = i + 1) {\n"
"        strSuffix = strSuffix + chars[i];\n"
"    }\n"
"\n"
"    return strSuffix == suffix;\n"
"}\n"
;

static const char STDLIB_TEST_SOURCE[] = 
"// ANSI color codes (using \\e for ESC character)\n"
"var RESET = \"\\e[0m\";\n"
"var BOLD = \"\\e[1m\";\n"
"var GREEN = \"\\e[32m\";\n"
"var RED = \"\\e[31m\";\n"
"var CYAN = \"\\e[36m\";\n"
"var GRAY = \"\\e[90m\";\n"
"\n"
"var testSuites = [];\n"
"var currentSuite = nil;\n"
"\n"
"// Enable test mode when module loads\n"
"__enterTestMode();\n"
"\n"
"export fun suite(name, fn) {\n"
"    print BOLD + CYAN + name + RESET;\n"
"    fn();\n"
"}\n"
"\n"
"export fun test(description, testFn) {\n"
"    __setCurrentTest(description);\n"
"    __clearLastFailure();\n"
"\n"
"    testFn();\n"
"\n"
"    if (__testFailed()) {\n"
"        var failure = __getLastFailure();\n"
"        print RED + \"  ✗ \" + RESET + GRAY + description + RESET;\n"
"        print RED + \"    \" + failure + RESET;\n"
"    } else {\n"
"        print GREEN + \"  ✓ \" + RESET + description;\n"
"    }\n"
"}\n"
"\n"
"export fun run() {\n"
"    __exitTestMode();\n"
"}\n"
;

const EmbeddedModule EMBEDDED_STDLIB[] = {
    {"stdlib/list", STDLIB_LIST_SOURCE, sizeof(STDLIB_LIST_SOURCE) - 1},
    {"stdlib/math", STDLIB_MATH_SOURCE, sizeof(STDLIB_MATH_SOURCE) - 1},
    {"stdlib/string", STDLIB_STRING_SOURCE, sizeof(STDLIB_STRING_SOURCE) - 1},
    {"stdlib/test", STDLIB_TEST_SOURCE, sizeof(STDLIB_TEST_SOURCE) - 1},
};

const int EMBEDDED_STDLIB_COUNT = 4;
