// AUTO-GENERATED FILE - DO NOT EDIT
// Generated from stdlib/*.cmel files by tools/embed_stdlib.sh
// This file is tracked in git for build convenience

#include "stdlib_embedded.h"

static const char STDLIB_CONVERT_SOURCE[] = 
"// Convert module - exports type conversion utilities\n"
"export var number = __number;\n"
;

static const char STDLIB_IO_SOURCE[] = 
"// I/O module - exports native I/O functions\n"
"export var clock = __clock;\n"
"export var input = __input;\n"
"export var readFile = __readFile;\n"
;

static const char STDLIB_LIST_SOURCE[] = 
"// List module - exports native list functions\n"
"import number from \"stdlib/convert\";\n"
"\n"
"export var slice = __slice;\n"
"\n"
"export fun createListWithDefaults(defaultElement, size) {\n"
"    var newList = [];\n"
"    for (var i = 0; i < size; i = i+1) {\n"
"        newList.add(defaultElement);\n"
"    }\n"
"    return newList;\n"
"}\n"
"\n"
"fun merge(nums, left, mid, right) {\n"
"    var n1 = mid - left + 1;\n"
"    var n2 = right - mid;\n"
"\n"
"    var leftTmp = createListWithDefaults(0, n1);\n"
"    var rightTmp = createListWithDefaults(0, n2);\n"
"\n"
"    for (var i = 0; i < n1; i = i+1) {\n"
"        leftTmp[i] = nums[left + i];\n"
"    }\n"
"    for (var i = 0; i < n2; i = i+1) {\n"
"        rightTmp[i] = nums[mid + 1 + i];\n"
"    }\n"
"\n"
"    var i = 0;\n"
"    var j = 0;\n"
"    var k = left;\n"
"\n"
"    while (i < n1 and j < n2) {\n"
"        if (leftTmp[i] <= rightTmp[j]) {\n"
"            nums[k] = leftTmp[i];\n"
"            i = i + 1;\n"
"        } else {\n"
"            nums[k] = rightTmp[j];\n"
"            j = j + 1;\n"
"        }\n"
"        k = k + 1;\n"
"    }\n"
"\n"
"    while (i < n1) {\n"
"        nums[k] = leftTmp[i];\n"
"        i = i + 1;\n"
"        k = k + 1;\n"
"    }\n"
"\n"
"    while (j < n2) {\n"
"        nums[k] = rightTmp[j];\n"
"        j = j + 1;\n"
"        k = k + 1;\n"
"    }\n"
"\n"
"    return nums;\n"
"}\n"
"\n"
"fun mergeWithComparator(nums, left, mid, right, comparator) {\n"
"    var n1 = mid - left + 1;\n"
"    var n2 = right - mid;\n"
"\n"
"    var leftTmp = createListWithDefaults(0, n1);\n"
"    var rightTmp = createListWithDefaults(0, n2);\n"
"\n"
"    for (var i = 0; i < n1; i = i+1) {\n"
"        leftTmp[i] = nums[left + i];\n"
"    }\n"
"    for (var i = 0; i < n2; i = i+1) {\n"
"        rightTmp[i] = nums[mid + 1 + i];\n"
"    }\n"
"\n"
"    var i = 0;\n"
"    var j = 0;\n"
"    var k = left;\n"
"\n"
"    while (i < n1 and j < n2) {\n"
"        if (comparator(leftTmp[i], rightTmp[j]) <= 0) {\n"
"            nums[k] = leftTmp[i];\n"
"            i = i + 1;\n"
"        } else {\n"
"            nums[k] = rightTmp[j];\n"
"            j = j + 1;\n"
"        }\n"
"        k = k + 1;\n"
"    }\n"
"\n"
"    while (i < n1) {\n"
"        nums[k] = leftTmp[i];\n"
"        i = i + 1;\n"
"        k = k + 1;\n"
"    }\n"
"\n"
"    while (j < n2) {\n"
"        nums[k] = rightTmp[j];\n"
"        j = j + 1;\n"
"        k = k + 1;\n"
"    }\n"
"\n"
"    return nums;\n"
"}\n"
"\n"
"fun mergeSort(nums, left, right) {\n"
"    if (left < right) {\n"
"        var mid = left + (right - left) / 2;\n"
"        // floor the number. Needs better approach\n"
"        mid = \"\" + mid;\n"
"        mid = mid.split(\".\");\n"
"        mid = number(mid[0]);\n"
"\n"
"        mergeSort(nums, left, mid);\n"
"        mergeSort(nums, mid + 1, right);\n"
"\n"
"        return merge(nums, left, mid, right);\n"
"    }\n"
"    return nums;\n"
"}\n"
"\n"
"fun mergeSortWithComparator(nums, left, right, comparator) {\n"
"    if (left < right) {\n"
"        var mid = left + (right - left) / 2;\n"
"        // floor the number. Needs better approach\n"
"        mid = \"\" + mid;\n"
"        mid = mid.split(\".\");\n"
"        mid = number(mid[0]);\n"
"\n"
"        mergeSortWithComparator(nums, left, mid, comparator);\n"
"        mergeSortWithComparator(nums, mid + 1, right, comparator);\n"
"\n"
"        return mergeWithComparator(nums, left, mid, right, comparator);\n"
"    }\n"
"    return nums;\n"
"}\n"
"\n"
"export fun sort(nums) {\n"
"    return mergeSort(nums, 0, nums.length() - 1);\n"
"}\n"
"\n"
"export fun sortWith(nums, comparator) {\n"
"    return mergeSortWithComparator(nums, 0, nums.length() - 1, comparator);\n"
"}\n"
;

static const char STDLIB_MATH_SOURCE[] = 
"// Math module - exports native math functions\n"
"export var PI = 3.14159265359;\n"
"export var E = 2.71828182846;\n"
"export var abs = __abs;\n"
"export var max = __max;\n"
"export var min = __min;\n"
"export var pow = __pow;\n"
"export var sqrt = __sqrt;\n"
;

static const char STDLIB_STRING_SOURCE[] = 
"// String module - exports native string functions\n"
"export var startsWith = __startsWith;\n"
"export var endsWith = __endsWith;\n"
"export var join = __join;\n"
"\n"
"// reverse is still pure CMEL implementation\n"
"export fun reverse(str) {\n"
"    var chars = str.split(\"\");\n"
"    var result = \"\";\n"
"    for (var i = chars.length() - 1; i >= 0; i = i - 1) {\n"
"        result = result + chars[i];\n"
"    }\n"
"    return result;\n"
"}\n"
;

static const char STDLIB_TEST_SOURCE[] = 
"// ANSI color codes (using \\e for ESC character)\n"
"var RESET = \"\\e[0m\";\n"
"var BOLD = \"\\e[1m\";\n"
"var GREEN = \"\\e[32m\";\n"
"var RED = \"\\e[31m\";\n"
"var CYAN = \"\\e[36m\";\n"
"var GRAY = \"\\e[90m\";\n"
"\n"
"var testSuites = [];\n"
"var currentSuite = nil;\n"
"\n"
"// Enable test mode when module loads\n"
"__enterTestMode();\n"
"\n"
"export fun suite(name, fn) {\n"
"    print BOLD + CYAN + name + RESET;\n"
"    fn();\n"
"}\n"
"\n"
"export fun test(description, testFn) {\n"
"    __setCurrentTest(description);\n"
"    __clearLastFailure();\n"
"\n"
"    testFn();\n"
"\n"
"    if (__testFailed()) {\n"
"        var failure = __getLastFailure();\n"
"        print RED + \"  ✗ \" + RESET + GRAY + description + RESET;\n"
"        print RED + \"    \" + failure + RESET;\n"
"    } else {\n"
"        print GREEN + \"  ✓ \" + RESET + description;\n"
"    }\n"
"}\n"
"\n"
"export fun run() {\n"
"    __exitTestMode();\n"
"}\n"
"\n"
"// Export assertion functions\n"
"export var assert = __assert;\n"
"export var assertEqual = __assertEqual;\n"
;

const EmbeddedModule EMBEDDED_STDLIB[] = {
    {"stdlib/convert", STDLIB_CONVERT_SOURCE, sizeof(STDLIB_CONVERT_SOURCE) - 1},
    {"stdlib/io", STDLIB_IO_SOURCE, sizeof(STDLIB_IO_SOURCE) - 1},
    {"stdlib/list", STDLIB_LIST_SOURCE, sizeof(STDLIB_LIST_SOURCE) - 1},
    {"stdlib/math", STDLIB_MATH_SOURCE, sizeof(STDLIB_MATH_SOURCE) - 1},
    {"stdlib/string", STDLIB_STRING_SOURCE, sizeof(STDLIB_STRING_SOURCE) - 1},
    {"stdlib/test", STDLIB_TEST_SOURCE, sizeof(STDLIB_TEST_SOURCE) - 1},
};

const int EMBEDDED_STDLIB_COUNT = 6;
